#!/usr/bin/env bash
# Answer the question by the right choice
What is the OSI model?
1- Set of specifications that network hardware manufacturers must respect

How is the OSI model organized?
From the lowest to the highest level